AWSTemplateFormatVersion: '2010-09-09'
Description: Secure S3 bucket for CodePipeline artifacts

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ArtifactBucketArn:
    Description: ARN of the Artifact S3 bucket
    Value: !GetAtt ArtifactBucket.Arn
    Export:
      Name: ArtifactBucketArn