version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install cfn-lint
  build:
    commands:
      - echo "Starting CloudFormation Linting..."
      - cfn-lint artifactbucket.yml pipeline.yml
artifacts:
  files:
    - '**/*'